---
title: "TaxNorm_Working_Example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(TaxNorm)
library(phyloseq)
library(microbiome)
```

```{r}
data("TaxNorm_Example_Input", package = "TaxNorm")

```

```{r}

coeff <- c(10,10)
mus <- c(10,10)
thetas <- c(10,10)
pis <- c(10,10)

model_params <- TaxNorm_Model_Parameters(coefficients = coeff,
                         mu = mus,
                         theta = thetas,
                         pi = pis)


res <- TaxNorm_Results(rawdata = mtcars,
                normdata = mtcars,
                ecdf = mtcars,
                model_pars = model_params,
                converge = c(TRUE,TRUE,FALSE))

```


```{r}
group <- sample_data(TaxNorm_Example_Input)$body_site
HMP_norm <- TaxNorm_Normalization(data = TaxNorm_Example_Input, 
                     depth = NULL,
                     group = group, 
                     filter.sample.num = 1,
                     filter.taxa.count = 0,
                     random = TRUE,
                     ncores = 1)
```


```{r}
counts_df <- as.data.frame(HMP_norm[[3]])
```

